# Generated by Django 4.2.7 on 2023-11-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='rate_type',
        ),
    ]
