# Generated by Django 4.2.7 on 2023-12-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source_alter_rate_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.SmallIntegerField(choices=[(1, 'USD'), (2, 'EUR')]),
        ),
    ]
