# Generated by Django 4.2.7 on 2023-12-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_rate_rate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=8)),
                ('time', models.DecimalField(decimal_places=3, max_digits=16)),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.SmallIntegerField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'GBP'), (4, 'PLN'), (5, 'CAD')]),
        ),
    ]
