# Generated by Django 4.2.7 on 2023-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_requestresponselog_alter_rate_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
